name: Deploy to IONOS via SFTP

on:
  push:
    branches:
      - main # Le déploiement se lancera à chaque push sur la branche main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      
      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: 📦 Install Dependencies
        run: npm ci
        
      - name: 🏗️ Build Project
        run: npm run build
        
      - name: 🚀 Sync files via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: './dist/*'
          remote_path: './okamilink/' # Dossier spécifié par l'utilisateur
